### ISSUE TITLE
not working well on other datasets

### ISSUE THREAD

**Issue by kracwarlock** [nashory/pggan-pytorch#19]
I've been trying to train this code on other datasets like ImageNet but the results are very bad. The images turn into almost black and grey blobs. However, using the original author's theano implementation, results on ImageNet are good. Have you tried out other datasets?

**Comment by sxyxf66** [comment]
@kracwarlock hi, do you know how to put my dataset? I alwanys faild to read the image files.
--train_data_root F:\pychqarmtestdemo\dataset\face
face fold includes many *.jog

Output:Renew dataloader configuration, load data from F:\pychqarmtestdemo\dataset\face.

it didn't begin to train.
 do you know why it seems like this? Would like your reply. Thanks.
