### ISSUE TITLE
AttributeError: 'Generator' object has no attribute 'module'

### ISSUE THREAD

**Issue by rahulbhalley** [nashory/pggan-pytorch#20]
The following is the error I get when the generator begins to grow:
```
Traceback (most recent call last):
  File "trainer.py", line 343, in <module>
    trainer.train()
  File "trainer.py", line 251, in train
    self.resl_scheduler()
  File "trainer.py", line 149, in resl_scheduler
    self.G.module.grow_network(floor(self.resl))
  File "/Users/rahulbhalley/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 366, in __getattr__
    type(self).__name__, name))
AttributeError: 'Generator' object has no attribute 'module'
```
Please help! Thanks in advance.

**Comment by rahulbhalley** [comment]
PyTorch version is `0.3.0.post4`.
And what is the equivalent of `self.G.module.grow_network(floor(self.resl))` in `0.3.0.post4` version of PyTorch if the code is not updated for `0.3.0.post4`?

**Comment by cynthia951031** [comment]
Have you find the solution? I met the same question and my PyTorch version is 0.4.0.

**Comment by rahulbhalley** [comment]
For eliminating this [somewhat] bug I rewrote the whole code in PyTorch 0.3.0 and uploaded it [here](
https://github.com/rahulbhalley/Progressive-Growing-of-GANs) in past. 

_Note: I am yet to update it for PyTorch 0.4.0 but it does run in PyTorch 0.3.0._
