### ISSUE TITLE
Which version of Pytorch should we use ?

### ISSUE THREAD

**Issue by superhans** [nashory/pggan-pytorch#45]
PyTorch 1.0, 0.3 and 0.4 all gave me annoying "compatibility" bugs. 

For example, Pytorch 1.0 gave me a 
```
pggan-pytorch/custom_layers.py", line 114, in forward
    return x + self.bias.view(1,-1,1,1).expand_as(x)
RuntimeError: expected type torch.cuda.FloatTensor but got torch.FloatTensor
```

Pytorch 0.4 gives me a RandomSampler based error, and after fixing it, I get : 
```
  File "torch/nn/functional.py", line 1537, in 
    return lambd_optimized(input, target, size_average, reduce)
RuntimeError: input and target shapes do not match: input [32 x 1], target [32] at /pytorch/aten/src/THCUNN/generic/MSECriterion.cu:15

```
Similarly with Pytorch 0.3 (it was a .item() error). So which version do you want us to use ?

**Comment by Djmcflush** [comment]
Try PyTorch 0.4.1 thats what im currently using to run it.
