### ISSUE TITLE
issue in dataloader.py

### ISSUE THREAD

**Issue by ZhilingYe** [nashory/pggan-pytorch#9]
row32:  transforms.Scale(**size=(self.imsize,self.imsize),**  interpolation=Image.NEAREST),

The requirement of size is a int, but here get a tuple.

**Comment by NilaiSarda** [comment]
Update your version of torchvision==0.2.0, this is resolved

**Comment by nashory** [comment]
@NilaiSarda thank you for your kind reply! :)
